spring:
  application:
    name: Othello Backend
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false
